version: '3.8'
services:
  #    zookeeper 与 kafka 搭配使用 版本要使用正确
  #    下面IP要写正确，自己本地电脑IP
  zookeeper:
    container_name: max-zookeeper
    image: zookeeper:3.4
    restart: always
    ports:
      - 2181:2181
    networks:
      - max-net
  kafka:
    container_name: max-kafka
    image: wurstmeister/kafka:2.12-2.1.0
    restart: always
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zookeeperhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeperhost:2181
    networks:
      - max-net
  beanstalkd1:
    image: schickling/beanstalkd
    container_name: max-beanstalkd1
    volumes:
      - ./data/beanstalkd/beanstalkd1_data:/data
    ports:
      - 11300:11300
    networks:
      - max-net
  beanstalkd2:
    image: schickling/beanstalkd
    container_name: max-beanstalkd2
    volumes:
      - ./data/beanstalkd/beanstalkd2_data:/data
    ports:
      - 11301:11300 # 注意这里docker端口一定为11300
    networks:
      - max-net
  beanstalkd-console:
    image: schickling/beanstalkd-console
    container_name: max-beanstalkd-console
    links:
      - "beanstalkd1"
      - "beanstalkd2"
    ports:
      - 2080:2080
    networks:
      - max-net
networks:
  max-net:
    ipam:
      config:
        - subnet: 172.15.0.0/24